{
 "title": "Proxmox VE",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "NVME Info", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 } },
  { "title": "SATA Info", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 6, "y": 0 } },
  {
   "title": "PVE Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /memused|memshared|memfree/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Available Spare Sectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available_spare\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read/Write Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"sata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"raw_read_error_rate\" or r[\"_field\"] == \"write_error_rate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m )\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] == \"critical_warning\" or r[\"_field\"] == \"unsafe_shutdowns\" or r[\"_field\"] == \"media_errors\" or r[\"_field\"] == \"num_err_log_entries\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m )\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"sata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reallocate_nand_blk_cnt\" or r[\"_field\"] == \"erase_fail_count\" \n                    or r[\"_field\"] == \"program_fail_count\" or r[\"_field\"] == \"error_correction_count\" \n                    or r[\"_field\"] == \"reallocated_event_count\" or r[\"_field\"] == \"udma_crc_error_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_units_read\" or r[\"_field\"] == \"data_units_written\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"sata\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_lbas_written\")\n  |> map(fn: (r) => ({r with _value: r._value * 512}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SATA Health Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"sata\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /raw_read_error_rate|write_error_rate|reallocate_nand_blk_cnt/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE Temperature Info",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"pve\" and\n    r._measurement == \"temp\" and\n    r._field !~ /core/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    },
    {
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.host == \"pve\" and\n    r.devtype == \"sata\" and\n    r._measurement == \"disks\" and\n    r._field == \"temperature_celsius\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_units_read_from_day1\" or r[\"_field\"] == \"data_units_written_from_day1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME Health Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /available_spare$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /critical_warning|media_errors/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVE Storage Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avail\")\n  |> filter(fn: (r) => r[\"host\"] == \"local-lvm\" or r[\"host\"] == \"synology-backup-ct-vm\" or r[\"host\"] == \"local\" or r[\"host\"] == \"proxmox-backup-server-sata-2TB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "NVME Num Err Log Entries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"pve-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disks\")\n  |> filter(fn: (r) => r[\"host\"] == \"pve\")\n  |> filter(fn: (r) => r[\"devtype\"] == \"nvme\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num_err_log_entries\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}